{{- if .Values.applications.demoApp.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: demo-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  sources:

    - repoURL: https://github.com/nvthiet1995/demo-helm-charts.git
      targetRevision: main
      path: charts/gitops-base
      helm:
        valueFiles:
          - $values/environments/dev/demo-values.yaml

    - repoURL: https://github.com/nvthiet1995/argocd-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.demoApp.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

{{- end }}