{{- if .Values.applications.externalSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: default

  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: {{ .Values.applications.externalSecrets.chartVersion }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.externalSecrets.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

{{- end }}